apiVersion: batch/v1
kind: Job
metadata:
  name: generate-cnpg-secrets
  namespace: {{ .Release.Namespace }}
  labels:
  annotations:
    # This is the magic that tells Helm to run this AFTER install and upgrade
    "helm.sh/hook": post-install,post-upgrade
    # Deletes the old job before running a new one on upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: generate-cnpg-secrets
    spec:
      restartPolicy: OnFailure
      containers:
        - name: generate-cnpg-secrets
          image: {{ .Values.secretsGenerator.image.name }}:{{ .Values.secretsGenerator.image.tag }}
          env:
            - name: TF_VAR_VAULT_KV_NAME
              value: {{ .Values.database.vaultConfiguration.kvName }}
            - name: TF_VAR_VAULT_KV_PREFIX
              value: "{{ .Values.database.vaultConfiguration.kvPrefix }}"
            - name: TF_VAR_RUSTFS_INSTANCE
              value: {{ .Values.gateway.hostname}}
            - name: SECRETS_TO_CREATE
              value: {{ include "db.secretDetails" . | fromYamlArray | toJson | quote}} 
          envFrom:
            - secretRef:
                name: vault-access
            
