{{- if and (include "rust-fs.hasExternalSecrets" .) .Values.vaultAuthentication.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rust-admin-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.vaultAuthentication.clusterSecretStoreName}}
    kind: ClusterSecretStore
  target:
    name: rust-admin-secret
  data:
  dataFrom:
  - extract:
      key: {{ .Values.s3Objects.kvNameToStoreSecrets }}/{{ include "rust-fs.admin.credentials.key_name_prefix" . }}/{{ .Values.rustFS.gateway.apiHostname }}/{{ include "rust-fs.admin.credentials.key_name" . }}
      conversionStrategy: Default
      decodingStrategy: None
{{- end }}