apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rust-admin-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.vaultNewObjectsStore.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: rust-admin-secret
  dataFrom:
  - extract:
      key: {{ .Values.vaultNewObjectsStore.kvName }}/{{ include "rust-fs.admin.credentials.key_name_prefix" . }}/{{ .Values.rustFS.gateway.apiHostname }}/{{ include "rust-fs.admin.credentials.key_name" . }}
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
