apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rust-fs-oauth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.vaultNewObjectsStore.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: rust-fs-oauth
  data:
  dataFrom:
  - extract:
      key: "{{ .Values.rustFS.generateAuthentikOAuthSecrets.kvPrefix}}/{{ .Values.rustFS.generateAuthentikOAuthSecrets.authentikHost | trimPrefix "https://" | trimPrefix "http://" }}/{{ include "rust-fs.authentikOAuthSecrets.key_name" . }}"
      conversionStrategy: Default
      decodingStrategy: None