{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "initial-secret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: initial-secret
type: Opaque
data:
  # Check if secret exists and has a access-key, otherwise generate a random 16-char string
  access-key: {{ if $existingSecret }}{{ index $existingSecret.data "access-key" }}{{ else }}{{ randAlphaNum 16 | b64enc }}{{ end }}
  
  # Check if secret exists and has a secret-key, otherwise generate a random 16-char string
  secret-key: {{ if $existingSecret }}{{ index $existingSecret.data "secret-key" }}{{ else }}{{ randAlphaNum 16 | b64enc }}{{ end }}
