apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rust-fs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: nfs-storage-static
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi