apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rust-fs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.rustFS.storage.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.rustFS.storage.size }}