{{- $admin := include "rust-fs.admin.credentials" . | fromYamlArray -}}
              {{- $oauth := include "rust-fs.authentikOAuthSecrets" . | fromYamlArray -}}
              {{- $combined := concat $admin $oauth -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: rustfs-generate-secrets
  namespace: {{ .Release.Namespace }}
  labels:
  annotations:
    # This is the magic that tells Helm to run this AFTER install and upgrade
    "helm.sh/hook": post-install,post-upgrade
    # Deletes the old job before running a new one on upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: generate-secrets
    spec:
      restartPolicy: OnFailure
      containers:
        - name: generate-secrets
          image: ghcr.io/stanislawhorna/vault-initial-secrets-generator:26.24.1
          env:
            - name: TF_VAR_VAULT_KV_NAME
              value: {{ .Values.s3Objects.kvNameToStoreSecrets }}
            - name: TF_VAR_VAULT_KV_PREFIX
              value: "{{ include "rust-fs.appName" . }}"
            - name: TF_VAR_RUSTFS_INSTANCE
              value: {{ .Values.rustFS.serverDomains}}
            - name: SECRETS_TO_CREATE
              value: {{ $combined | toJson | quote}} 
          envFrom:
            - secretRef:
                name: tf-vault-access
            
