{{- if include "forgejo.hasExternalSecrets" . }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-access
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretsGenerator.vaultAccess.externalSecret.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: vault-access
  dataFrom:
  - extract:
      key: {{ .Values.secretsGenerator.vaultAccess.externalSecret.kvName }}
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
{{- end }}
