apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce 
  {{- if .Values.netbox.persistence.media.storageClass }}
  storageClassName: {{ .Values.netbox.persistence.media.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.netbox.persistence.media.size }}
