apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: email-account
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.emailCredentials.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: email-account
    template:
      engineVersion: v2
      data:
        AUTHENTIK_EMAIL__HOST: "{{ `{{ .email_host }}` }}"
        AUTHENTIK_EMAIL__PORT: "{{ `{{ .email_port }}` }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ `{{ .email }}` }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ `{{ .password }}` }}"
        AUTHENTIK_EMAIL__USE_TLS: "{{ `{{ .use_tls }}` }}"
        AUTHENTIK_EMAIL__USE_SSL: "{{ `{{ .use_ssl }}` }}"
        AUTHENTIK_EMAIL__FROM: "{{ `{{ .email }}` }}"
  dataFrom:
  - extract:
      key: "{{ .Values.emailCredentials.path }}"
      conversionStrategy: Default
      decodingStrategy: None