apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/name: argocd-application-controller
spec:
  replicas: {{ .Values.controller.replicaCount }}
  serviceName: argocd-application-controller
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-application-controller
    spec:
      serviceAccountName: argocd-application-controller
      serviceAccountName: argocd-application-controller
      containers:
        - name: argocd-application-controller
          image: "{{ .Values.images.argocd.repository }}:{{ .Values.images.argocd.tag }}"
          imagePullPolicy: {{ .Values.images.argocd.pullPolicy }}
          command: ["argocd-application-controller"]
          envFrom:
            - configMapRef:
                name: argocd-cmd-params-cm
                optional: true
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}