{{- if and (.Capabilities.APIVersions.Has "postgresql.cnpg.io/v1") .Values.database.backup.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "outline.db.clusterName" . }}-scheduled-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.database.backup.schedule | quote }}
  backupOwnerReference: self
  cluster:
    name: {{ include "outline.db.clusterName" . }}
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
{{- end }}