apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "outline.db.clusterName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1
  
  storage:
    size: 5Gi
    storageClass: {{ .Values.database.storageClass }}
  
  bootstrap:
    initdb:
      database: {{ include "outline.db.databaseName" . }}
      owner: {{ include "outline.db.username" . }}
      secret:
        name: db-creds
  
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: outline-s3-store

