apiVersion: batch/v1
kind: Job
metadata:
  name: 1-cnpg-generate-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    # This is the magic that tells Helm to run this AFTER install and upgrade
    "helm.sh/hook": post-install,post-upgrade
    # Deletes the old job before running a new one on upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: generate-secrets
          image: {{ .Values.secretsGenerator.image.name }}:{{ .Values.secretsGenerator.image.tag }}
          env:
            - name: TF_VAR_VAULT_KV_NAME
              value: {{ .Values.secretsGenerator.kvName }}
            - name: TF_VAR_VAULT_KV_PREFIX
              value: "{{ .Values.database.kvPrefix }}"
            - name: SECRETS_TO_CREATE
              value: {{ include "outline.db.secretDetails" . | fromYamlArray | toJson | quote}} 
          envFrom:
            - secretRef:
                name: vault-access
            
