apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lgtm-stack.componentConfig" . }}
  namespace: {{ .Release.Namespace }}
data:
  custom.ini: |
{{- if .Values.grafana.config }}
{{ .Values.grafana.config | indent 4 }}
{{- else }}
{{ include "lgtm-stack.grafanaDefaultConfig" . | indent 4 }}
{{- end }}
