apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-access
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.grafana.secretsGenerator.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: vault-access
  data:
  dataFrom:
  - extract:
      key: {{ .Values.grafana.secretsGenerator.vaultAccess.externalSecret.kvName }}
      conversionStrategy: Default
      decodingStrategy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.grafana.secretsGenerator.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: grafana-oauth-secrets
  data:
  dataFrom:
  - extract:
      key: "{{ .Values.grafana.generateAuthentikOAuthSecrets.kvPrefix}}/{{ .Values.grafana.generateAuthentikOAuthSecrets.authentikHost | trimPrefix "https://" | trimPrefix "http://" }}/{{ include "lgtm-stack.grafana.authentikOAuthSecrets.key_name" . }}"
      conversionStrategy: Default
      decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.grafana.secretsGenerator.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: grafana-admin-creds
  data:
  dataFrom:
  - extract:
      key: "{{ .Values.grafana.defaultAdminCredentials.kvPrefix }}/{{ .Values.grafana.rootUrl | trimPrefix "https://" | trimPrefix "http://" }}/{{ include "lgtm-stack.grafana.defaultAdminCredentials.key_name" . }}"
      conversionStrategy: Default
      decodingStrategy: None
