{{- if and (include "lgtm-stack.hasExternalSecrets" .) .Values.grafana.selfSingedRootCA.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: self-signed-root-ca
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.grafana.selfSingedRootCA.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: self-signed-root-ca
  data:
    - secretKey: root-ca.crt
      remoteRef:
        key: {{ .Values.grafana.selfSingedRootCA.kvName }}
        property: {{ .Values.grafana.selfSingedRootCA.certificateProperty }}
{{- end }}
