apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lgtm-stack.componentPVC" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce 
  {{- if .Values.grafana.persistence.storageClass }}
  storageClassName: {{ .Values.grafana.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
