{{- if .Values.grafana.defaultAdminCredentials.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-generate-admin-secrets
  namespace: {{ .Release.Namespace }}
  labels:
  annotations:
    # This is the magic that tells Helm to run this AFTER install and upgrade
    "helm.sh/hook": post-install,post-upgrade
    # Deletes the old job before running a new one on upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: grafana-generate-admin-secrets
    spec:
      restartPolicy: OnFailure
      containers:
        - name: generate-secrets
          image: {{ .Values.grafana.secretsGenerator.image.name }}:{{ .Values.grafana.secretsGenerator.image.tag }}
          env:
            - name: TF_VAR_VAULT_KV_NAME
              value: {{ .Values.grafana.secretsGenerator.kvName }}
            - name: TF_VAR_VAULT_KV_PREFIX
              value: "{{ .Values.grafana.defaultAdminCredentials.kvPrefix}}"
            - name: SECRETS_TO_CREATE
              value: {{ include "lgtm-stack.grafana.defaultAdminCredentials" . | fromYamlArray | toJson | quote}} 
          envFrom:
            - secretRef:
                name: vault-access
            
{{- end }}