apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trek.appName" . }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.data.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trek.appName" . }}-uploads
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.uploads.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trek.appName" . }}-backups
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.backups.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.size }}
