apiVersion: v1
kind: Service
metadata:
  name: {{ include "trek.serviceName" . }}
  labels:
    {{- include "trek.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "trek.http.port" . }}
      targetPort: {{ include "trek.http.port" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "trek.labels" . | nindent 4 }}
