{{- $persistenceList := include "immich.persistenceList" . | fromYamlArray -}}
{{- range $persistenceList }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .storageClass }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}