image:
  tag: v0.29.0
resources:
  requests:
    memory: "32Mi"
    cpu: "50m"
  limits:
    memory: "64Mi"
    cpu: "100m"

externalSecret:
  enabled: true
  ClusterSecretStoreName: "hcp-vault-secret-store"
  kvName: "synology-credentials"
  username: "DSM_USERNAME"
  password: "DSM_PASSWORD"
  privatePassword: "DSM_PRIV_PASSWORD"

defaultSnmpSettings:
  version: 3
  security_level: authPriv
  auth_protocol: SHA
  priv_protocol: DES

synologyDevices:
  - name: "NAS-01"
    ip: "192.168.0.101"
    externalSecret:
      kvName: "synology-credentials/NAS-01"
  - name: "NAS-02"
    ip: "192.168.0.102"
    externalSecret:
      kvName: "synology-credentials/NAS-02"
