apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-files
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  {{- $files := .Files.Glob "files/terraform/*.tf" }}
  {{- range $path, $bytes := $files }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
