apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tf-vault-access
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.vaultAuthentication.clusterSecretStoreName}}
    kind: ClusterSecretStore
  target:
    name: tf-vault-access
  data:
  dataFrom:
  - extract:
      key: {{ .Values.vaultAuthentication.keyPath }}
      conversionStrategy: Default
      decodingStrategy: None
