{{- if include "forgejo.hasExternalSecrets" . }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretsGenerator.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: db-creds
  dataFrom:
  - extract:
      key: "{{ .Values.database.kvPrefix}}/{{ .Values.gateway.hostname }}/{{ include "forgejo.db.secretDetails.key_name" . }}"
      conversionStrategy: Default
      decodingStrategy: None

{{- if and (.Values.database.backup.enabled) .Values.database.backup.s3Config.credentialsInVault.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-s3-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretsGenerator.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: cnpg-backup-s3-credentials
  dataFrom:
  - extract:
      key: "{{ .Values.database.backup.s3Config.credentialsInVault.path }}"
      conversionStrategy: Default
      decodingStrategy: None
{{- end }}
{{- end }}
