{{- if and (include "lgtm-stack.hasExternalSecrets" .) .Values.mimir.longTermStorage.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-s3-creds
  namespace: {{ .Release.Namespace}}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.mimir.longTermStorage.externalSecret.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: mimir-s3-creds
  data:
  - remoteRef:
      key: {{ .Values.mimir.longTermStorage.externalSecret.kvName }}
      property: {{ .Values.mimir.longTermStorage.externalSecret.accessKeyName }}
    secretKey: "access-key"
  - remoteRef:
      key: {{ .Values.mimir.longTermStorage.externalSecret.kvName }}
      property: {{ .Values.mimir.longTermStorage.externalSecret.secretKeyName }}
    secretKey: "secret-key"
{{- end -}}