{{ if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: forgejo-server-http-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io	
      kind: Gateway
      name: {{ .Values.gateway.gatewayName}}
      namespace: {{ .Values.gateway.gatewayNamespace }}
      sectionName: web
  hostnames:
    - {{ .Values.gateway.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      {{- if .Values.gateway.allowHttp }}
      backendRefs:
        - name: {{ include "forgejo.server.serviceName" . }}
          port: {{ include "forgejo.server.http.port" . }}
      {{- else }}
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            port: 443
            statusCode: 301
      {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: forgejo-server-https-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io	
      kind: Gateway
      name: {{ .Values.gateway.gatewayName }}
      namespace: {{ .Values.gateway.gatewayNamespace }}
      sectionName: websecure
  hostnames:
    - {{ .Values.gateway.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "forgejo.server.serviceName" . }}
          port: {{ include "forgejo.server.http.port" . }}
{{ end }}