apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vikunja.appName" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vikunja.deployment.labels" . | nindent 4 }}
data:
  config.yml: |
    auth:
      local:
        enabled: false
      openid:
        enabled: true
        providers:
          authentik:
            name: "Login using Authentik"
            authurl: "https://authentik.prod.horna.local"
            clientid: "vikunja"
            scope:
              - openid
              - profile
              - email
              - entitlements
              - groups
