apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vikunja.appName" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vikunja.deployment.labels" . | nindent 4 }}
data:
  VIKUNJA_SERVICE_TIMEZONE: "Europe/Warsaw"
  VIKUNJA_SERVICE_PUBLICURL: {{ .Values.gateway.rootUrl | quote }}
  VIKUNJA_DATABASE_PATH: /db/vikunja.db
  SSL_CERT_FILE: /etc/ssl/certs/root-ca.crt
