apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-access
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretsGenerator.vaultAccess.externalSecret.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: vault-access
  dataFrom:
  - extract:
      key: {{ .Values.secretsGenerator.vaultAccess.externalSecret.path }}
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
{{- if .Values.emailCredentials.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{include "vikunja.appName" .}}-email-account
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.emailCredentials.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{include "vikunja.appName" .}}-email-account
    template:
      engineVersion: v2
      data:
        VIKUNJA_MAILER_ENABLED: "true"
        VIKUNJA_MAILER_HOST: "{{ `{{ .email_host }}` }}"
        VIKUNJA_MAILER_PORT: "{{ `{{ .email_port }}` }}"
        VIKUNJA_MAILER_USERNAME: "{{ `{{ .email }}` }}"
        VIKUNJA_MAILER_PASSWORD: "{{ `{{ .password }}` }}"
        VIKUNJA_MAILER_FROMEMAIL: "{{ `{{ .email }}` }}"
  dataFrom:
  - extract:
      key: "{{ .Values.emailCredentials.path }}"
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
{{- end }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "vikunja.appName" . }}-oauth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretsGenerator.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "vikunja.appName" . }}-oauth
    template:
      engineVersion: v2
      data:
        config.yml: |
          auth:
            local:
              enabled: false
            openid:
              enabled: {{ `{{ .VIKUNJA_AUTH_OPENID_ENABLED }}` }}
              providers:
                authentik:
                  name: "{{ `{{ .VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_NAME }}` }}"
                  authurl: "{{ `{{ .VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_AUTHURL }}` }}/application/o/vikunja/"
                  clientid: "{{ `{{ .VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_CLIENTID }}` }}"
                  clientsecret: "{{ `{{ .VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_CLIENTSECRET }}` }}"
                  scope: "{{ `{{ .VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_SCOPE }}` }}"
  dataFrom:
  - extract:
      key: "{{ .Values.generateAuthentikOAuthSecrets.kvPrefix}}/{{ .Values.generateAuthentikOAuthSecrets.authentikHost | trimPrefix "https://" | trimPrefix "http://" }}/{{ include "vikunja.authentikOAuthSecrets.key_name" . }}"
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None