apiVersion: v1
kind: Service
metadata:
  name: {{ include "vikunja.serviceName" . }}
  labels:
    {{- include "vikunja.deployment.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "vikunja.http.port" . }}
      targetPort: {{ include "vikunja.http.port" . }}
      protocol: TCP
  selector:
    {{- include "vikunja.deployment.labels" . | nindent 4 }}