grafana:
  renderingTimezone: Europe/Warsaw
  rootUrl: https://grafana.example.com
  provisionDashboards: true
  provisionDatasources: true
  gateway:
    enabled: true
    gatewayName: traefik-gateway
    gatewayNamespace: traefik
    allowHttp: false
  image:
    tag: 12.4.1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path-static
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
  # Override default datasources here
  # datasources: |
  #   apiVersion: 1
  #   datasources:
  #     - name: Custom Loki
  #       type: loki
  #       url: http://custom-loki:3100

loki:
  image:
    tag: 3.5.5
  persistence:
    enabled: true
    size: 20Gi
    storageClass: local-path-static
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  cacheResources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

mimir:
  image:
    tag: 2.17.1
  logLevel: warn
  persistence:
    enabled: true
    size: 50Gi
    storageClass: local-path-static
  longTermStorage:
    enabled: true
    s3Endpoint: "rust-fs.rust-fs.svc.cluster.local:9000"
    s3Bucket: "mimir-data"
    s3Insecure: false
    
    externalSecret:
      enabled: true
      ClusterSecretStoreName: "hcp-vault-secret-store"
      kvName: "rust-fs/mimir"
      secretKeyName: "secret-key"
      accessKeyName: "access-key"


  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "2Gi"
      cpu: "2"
  cacheResources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

tempo:
  image:
    tag: 2.9.0-rc.0
  persistence:
    enabled: true
    size: 50Gi
    storageClass: local-path-static
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"

    limits:
      memory: "512Mi"
      cpu: "1"
  cacheResources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

alloy:
  fullnameOverride: "alloy"
  service:
    enabled: false
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "750m"
    configMap:
      create: false
      name: alloy-config
  controller:
    type: daemonset
  rbac:
    create: true
  configReloader:
    resources:
      requests:
        memory: "50Mi"
        cpu: "10m"
      limits:
        memory: "100Mi"
        cpu: "20m"

prometheus-node-exporter:
  fullnameOverride: "node-exporter"
  prometheus:
    monitor:
      enabled: true

kube-state-metrics:
  fullnameOverride: "kube-state-metrics"
  prometheus:
    monitor:
      enabled: true
