apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "immich.ml.cache.pvcName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: {{ .Values.immichMachineLearning.persistence.cache.storageClass }}
  resources:
    requests:
      storage: {{ .Values.immichMachineLearning.persistence.cache.size }}
