apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lgtm-stack.componentConfig" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lgtm-stack.labels" . | nindent 4 }}
data:
  config.alloy: |
{{ include "lgtm-stack.alloyDefaultConfig" . | indent 4 }}
