{{- if and (include "omada-exporter.hasExternalSecrets" .) .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omada-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecret.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: omada-secrets
  data:
    - secretKey: OMADA_CLIENT_ID
      remoteRef:
        key: {{ .Values.externalSecret.kvName }}
        property: {{ .Values.externalSecret.omadaClientIdKey }}
    - secretKey: OMADA_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.kvName }}
        property: {{ .Values.externalSecret.omadaClientSecret }}
    - secretKey: OMADA_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.kvName }}
        property: {{ .Values.externalSecret.omadaUsername }}
    - secretKey: OMADA_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.kvName }}
        property: {{ .Values.externalSecret.omadaPassword }}
    - secretKey: OMADA_SITE_NAME
      remoteRef:
        key: {{ .Values.externalSecret.kvName }}
        property: {{ .Values.externalSecret.omadaSiteName }}

{{- end }}
