apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentik.worker.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authentik.deployment.worker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    # --- Core Worker Ports ---
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000
    - name: metrics
      protocol: TCP
      port: 9300
      targetPort: 9300

    # --- Authentik Proxy Outpost Ports ---
    - name: proxy-http
      protocol: TCP
      port: 9000
      targetPort: 9001
    - name: proxy-https
      protocol: TCP
      port: 9443
      targetPort: 9444

    # --- Authentik LDAP Outpost Ports ---
    - name: ldap
      protocol: TCP
      port: 389
      targetPort: 3389
    - name: ldaps
      protocol: TCP
      port: 636
      targetPort: 6636

    # --- Authentik Radius Outpost Ports ---
    - name: radius
      protocol: UDP
      port: 1812
      targetPort: 1812
  selector:
    {{- include "authentik.deployment.worker.labels" . | nindent 4 }}