apiVersion: v1
kind: Service
metadata:
  name: {{ include "cache.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cache.appName" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "cache.port" . }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app: {{ include "cache.appName" . }}