localPath:
  storageClasses:
    - name: local-storage
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Delete
    - name: local-storage-static
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Retain
      pathPattern: "{{ .PVC.Namespace }}-{{ .PVC.Name }}"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

csi-driver-nfs:
  enabled: false
  kubeletDir: /var/lib/k0s/kubelet # default: /var/lib/kubelet/pods
  controller:
    enableSnapshotter: false
  storageClasses:
    - name: nfs-storage-static
      parameters:
        server: <nfs-server-ip>
        share: /<directory>/<path>
        subDir: ${pvc.metadata.namespace}-${pvc.metadata.name}
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
    - name: nfs-storage
      parameters:
        server: <nfs-server-ip>
        share: /<directory>/<path>
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
