localPath:
  storageClassName: local-storage
  volumeBindingMode: WaitForFirstConsumer
  reclaimPolicy: Delete
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

csi-driver-nfs:
  enabled: false
  kubeletDir: /var/lib/k0s/kubelet # default: /var/lib/kubelet/pods
  controller:
    enableSnapshotter: false
  storageClass:
    create: true
    name: nfs-storage
    parameters:
      server: <nfs-server-ip>
      share: /<nfs>/<server>/<path>
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
