{{- if and (include "pve-exporter.hasExternalSecrets" .) .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pve-exporter-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecret.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: pve-exporter-config
    template:
      engineVersion: v2
      data:
        pve.yml: |
{{- range .Values.pveServers }}

          {{ .name }}:
            user: {{ printf "{{ .%s_user }}" (.name | replace "-" "_") }}
            token_name: {{ printf "{{ .%s_tokenName }}" (.name | replace "-" "_") }}
            token_value: {{ printf "{{ .%s_tokenValue }}" (.name | replace "-" "_") }}
            verify_ssl: {{ .verifySsl | default $.Values.externalSecret.verifySsl }}
{{- end }}
  data:
{{- range .Values.pveServers }}
  {{- $serverExternalSecret := .externalSecret | default dict }}
  {{- $kvName := $serverExternalSecret.kvName | default $.Values.externalSecret.kvName }}
  {{- $safeName := .name | replace "-" "_" }}
    - secretKey: {{ $safeName }}_user
      remoteRef:
        key: {{ $kvName }}
        property: {{ $serverExternalSecret.user | default $.Values.externalSecret.user }}
    - secretKey: {{ $safeName }}_tokenName
      remoteRef:
        key: {{ $kvName }}
        property: {{ $serverExternalSecret.tokenName | default $.Values.externalSecret.tokenName }}
    - secretKey: {{ $safeName }}_tokenValue
      remoteRef:
        key: {{ $kvName }}
        property: {{ $serverExternalSecret.tokenValue | default $.Values.externalSecret.tokenValue }}
{{- end }}
{{- end }}
