apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-env-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "netbox.appName" . }}
data:
  SKIP_SUPERUSER: "false"
  SOCIAL_AUTH_OIDC_LABEL: "Log in with Authentik"
  REMOTE_AUTH_ENABLED: "true"
  REMOTE_AUTH_BACKEND: "social_core.backends.open_id_connect.OpenIdConnectAuth"
  REMOTE_AUTH_AUTO_CREATE_USER: "true"
  SOCIAL_AUTH_OIDC_USERNAME_KEY: "preferred_username"
  SOCIAL_AUTH_OIDC_SCOPE: "['openid', 'profile', 'email', 'groups']"
  AUTHENTIK_ADMIN_GROUP: "{{ .Values.generateAuthentikOAuthSecrets.adminGroupName }}"
  AUTHENTIK_VIEWER_GROUP: "{{ .Values.generateAuthentikOAuthSecrets.viewerGroupName }}"
  
  CORS_ORIGIN_ALLOW_ALL: "true"
  ALLOWED_HOSTS: "'*'"
  MEDIA_ROOT: "{{ include "netbox.mediaRoot" . }}"
  METRICS_ENABLED: "true"

  DB_HOST: {{ include "db.hostname" . }}
  DB_NAME: {{ include "db.databaseName" . }}
  DB_USER: {{ include "db.username" . }}

  REDIS_HOST: {{ include "cache.serviceName" . }}
  REDIS_CACHE_HOST: {{ include "cache.serviceName" . }}
  REDIS_DATABASE: "0"
  REDIS_CACHE_DATABASE: "1"

  GRAPHQL_ENABLED: "true"

  GRANIAN_WORKERS: "4"
  GRANIAN_BACKPRESSURE: "4"
