{{- $bootstrap := include "netbox.bootstrap" . | fromYamlArray -}}
              {{- $oauth := include "netbox.oauth" . | fromYamlArray -}}
              {{- $combined := concat $bootstrap $oauth -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: bootstrap-app-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    # This is the magic that tells Helm to run this AFTER install and upgrade
    "helm.sh/hook": post-install,post-upgrade
    # Deletes the old job before running a new one on upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: bootstrap-app-secrets
          image: {{ .Values.secretsGenerator.image.name }}:{{ .Values.secretsGenerator.image.tag }}
          env:
            - name: TF_VAR_VAULT_KV_NAME
              value: {{ .Values.secretsGenerator.kvName }}
            - name: TF_VAR_VAULT_KV_PREFIX
              value: "{{ .Values.secretsGenerator.kvPrefix }}"
            - name: SECRETS_TO_CREATE 
              value: {{ $combined | toJson | quote}} 
          envFrom:
            - secretRef:
                name: vault-access
            
