{{- if include "vaultIntegration.hasExternalSecrets" . -}}
{{- $global := . -}} {{/* Save the global context to access .Values inside the loop */}}
{{- range .Values.SecretStore }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
spec:
  provider:
    vault:
      server: {{ $global.Values.vaultAccess.server }}
      path: {{ .path }}
      version: {{ .version }}
      auth:
        {{- if $global.Values.vaultAccess.auth.appRole.enabled }}
        appRole:
          path: {{ $global.Values.vaultAccess.auth.appRole.path }}
          roleId: {{ $global.Values.vaultAccess.auth.appRole.roleId }}
          secretRef:
            name: {{ $global.Values.vaultAccess.auth.appRole.secretRef.name }}
            key: {{ $global.Values.vaultAccess.auth.appRole.secretRef.key }}
            namespace: {{ $global.Release.Namespace }}
        {{- end }}
{{- end }}
{{- end }}