apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "db.clusterName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1

  storage:
    size: {{ .Values.database.storage.size }}
    storageClass: {{ .Values.database.storage.storageClass }}

  imageName: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23

  postgresUID: 999
  postgresGID: 999

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    initdb:
      database: {{ include "db.databaseName" . }}
      owner: {{ include "db.username" . }}
      secret:
        name: db-creds
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS cube CASCADE;
        - ALTER USER "{{ include "db.username" . }}" WITH SUPERUSER;
        - ALTER DATABASE "{{ include "db.databaseName" . }}" OWNER TO "{{ include "db.username" . }}";
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
