apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.database.vaultConfiguration.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: db-creds
  dataFrom:
  - extract:
      key: "{{ .Values.database.vaultConfiguration.kvPrefix}}/{{ .Values.gateway.hostname }}/{{ include "db.SecretDetails.key_name" . }}"
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None