apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lgtm-stack.componentConfig" . }}
  labels:
    app: {{ include "lgtm-stack.componentAppName" . }}
data:
  config.yaml: |
{{ include "lgtm-stack.LokiDefaultConfig" . | indent 4 }}
