{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1" -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "outline.appSecret.key_name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretsGenerator.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "outline.appSecret.key_name" . }}
  dataFrom:
  - extract:
      key: "{{ .Values.outline.appSecret.kvPrefix}}/{{ .Values.outline.rootURL | trimPrefix "https://" | trimPrefix "http://" }}/{{ include "outline.appSecret.key_name" . }}"
      conversionStrategy: Default
      decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-url
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretsGenerator.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: db-url
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ `{{ .username }}` }}:{{ `{{ .password | urlquery }}` }}@{{ `{{ .hostname }}` }}:5432/{{ `{{ .database }}` }}?schema=public"
  dataFrom:
  - extract:
      key: "{{ .Values.database.kvPrefix}}/{{ .Values.gateway.hostname }}/{{ include "outline.db.secretDetails.key_name" . }}"
      conversionStrategy: Default
      decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-access
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretsGenerator.vaultAccess.externalSecret.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: vault-access
  dataFrom:
  - extract:
      key: {{ .Values.secretsGenerator.vaultAccess.externalSecret.kvName }}
      conversionStrategy: Default
      decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-data-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.storage.s3Config.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: s3-data-credentials
  dataFrom:
  - extract:
      key: {{ .Values.storage.s3Config.kvName }}
      conversionStrategy: Default
      decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-oauth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretsGenerator.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: outline-oauth
  data:
  dataFrom:
  - extract:
      key: "{{ .Values.outline.generateAuthentikOAuthSecrets.kvPrefix}}/{{ .Values.outline.generateAuthentikOAuthSecrets.authentikHost | trimPrefix "https://" | trimPrefix "http://" }}/{{ include "outline.authentikOAuthSecrets.key_name" . }}"
      conversionStrategy: Default
      decodingStrategy: None
{{- end }}