apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-access
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretsGenerator.vaultAccess.externalSecret.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: vault-access
  dataFrom:
  - extract:
      key: {{ .Values.secretsGenerator.vaultAccess.externalSecret.kvName }}
      conversionStrategy: Default
      decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretsGenerator.ClusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: argocd-secret
  dataFrom:
  - extract:
      key: "{{ .Values.bootstrap.kvPrefix}}/{{ .Values.gateway.hostname }}/{{ include "argocd.bootstrap.key_name" . }}"
      conversionStrategy: Default
      decodingStrategy: None
  - extract:
      key: "{{ .Values.generateAuthentikOAuthSecrets.kvPrefix}}/{{ .Values.generateAuthentikOAuthSecrets.authentikHost | trimPrefix "https://" | trimPrefix "http://" }}/{{ include "argocd.authentikOAuthSecrets.key_name" . }}"
      conversionStrategy: Default
      decodingStrategy: None

