{
 "title": "Mimir",
 "tags": [
  "Mimir",
  "LGTM"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "container", "query": "mimir" }
  ]
 },
 "panels": [
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container=\"$container\"}[5m])) by (container)",
     "legendFormat": "CPU"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\", exported_container=\"$container\"})",
     "legendFormat": "LIMIT"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cortex_build_info{job=\"mimir-svc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_pod_created{exported_pod=~\"$container.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received queries rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(increase(cortex_query_frontend_queries_total[$__interval]))",
     "legendFormat": "queries"
    }
   ]
  },
  {
   "title": "Active data series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cortex_ingester_active_series{container=\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Samples in total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cortex_distributor_samples_in_total{container=\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_querier_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_querier_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(cortex_querier_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Samples ingestion rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_ingested_samples_total{container=\"$container\"}[$__rate_interval]))",
     "legendFormat": "samples"
    }
   ]
  },
  {
   "title": "Compaction Lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(cortex_compactor_last_successful_run_timestamp_seconds{container=\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", container=\"$container\"}) ",
     "legendFormat": "Memory"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"memory\", exported_container=\"$container\"})",
     "legendFormat": "LIMIT"
    }
   ]
  },
  {
   "title": "Received queries rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cortex_query_frontend_queries_total[$__rate_interval]))",
     "legendFormat": "queries"
    }
   ]
  },
  {
   "title": "Blocks in local Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cortex_bucket_store_blocks_loaded{container=\"$container\"})",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Query cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (request_type) (rate(cortex_frontend_query_result_cache_hits_total{container=\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Metadata query latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(cortex_distributor_query_duration_seconds_bucket[5m]))by(le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(cortex_distributor_query_duration_seconds_bucket[5m]))by(le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5,sum(rate(cortex_distributor_query_duration_seconds_bucket[5m]))by(le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Query plan latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (stage) (rate(cortex_mimir_query_engine_plan_stage_latency_seconds_sum{container=\"$container\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Long-term storage index load time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_bucket_index_load_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_bucket_index_load_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(cortex_bucket_index_load_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Total Query Latency (method, code, route)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, status_code, route)(rate(cortex_querier_request_duration_seconds_sum{container=\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{method}}[{{status_code}}] {{route}}"
    }
   ]
  }
 ]
}