{
 "title": "Loki",
 "tags": [ "Loki" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(loki_build_info,instance)"
    }
   },
   {
    "name": "jobs",
    "query": {
     "query": "label_values(loki_build_info,job)"
    }
   },
   { "name": "interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "loki_build_info{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$jobs\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Local Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_size_bytes_sum{instance=\"$instance\"}) +\nsum(loki_ingester_memory_streams_labels_bytes{instance=\"$instance\"}) +\nsum(loki_ingester_wal_bytes_in_use{instance=\"$instance\"}) +\nsum(loki_ingester_wal_logged_bytes_total{instance=\"$instance\"}) +\nsum(loki_ingester_wal_recovered_bytes_total{instance=\"$instance\"}) +\nsum(loki_chunk_store_stored_chunk_bytes_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Loki - TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "loki_tcp_connections{job=\"$jobs\",instance=\"$instance\"}",
     "legendFormat": "{{ protocol }}"
    }
   ]
  },
  {
   "title": "Loki API - Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket{job=\"$jobs\",instance=\"$instance\"}[$__rate_interval])) by (le,method,route,status_code))",
     "legendFormat": "{{ method }} / {{ route }} / {{ status_code }}"
    }
   ]
  },
  {
   "title": "Loki API - Request Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_message_bytes_bucket{job=\"$jobs\",instance=\"$instance\"}[$__rate_interval])) by (le,method,route))",
     "legendFormat": "{{ method }} / {{ route }}"
    }
   ]
  },
  {
   "title": "Loki LogQL - Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(logql_query_duration_seconds_bucket{job=\"$jobs\",instance=\"$instance\"}[$__rate_interval])) by (le,query_type))",
     "legendFormat": "{{ query_type }}"
    }
   ]
  },
  {
   "title": "Loki LogQL - Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket{job=\"$jobs\",instance=\"$instance\"}[$__rate_interval])) by (le,type,status_code))",
     "legendFormat": "{{ type }} / {{ status_code }}"
    }
   ]
  }
 ]
}